---

- name: Copy the anomaly detection artifact
  copy: src={{ anomaly_detection_module_artifact }} dest={{ anomaly_detection_lib_path }}
  tags:
    - dataproducts

- name: Installing pip-3.8
  pip:
    name: "{{ anomaly_detection_lib_path }}/{{ anomaly_detection_module_artifact }}"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "python3.8"

- name: copy query config to config.json
  template: src="config.json.j2" dest="{{ virtualenv_path }}/config.json"
  with_items: "{{ anomaly_detection_queries | list }}"

- name: execute_anomaly_detection
  shell: "source {{virtualenv_path}}/bin/activate && nohup anomaly_detection druid_anomaly_detection --config_file={{ anomaly_detection_job_config_file }} --data_dir={{ anomaly_detection_data_dir }} --druid_broker_host={{ sunbird_druid_broker_host }} --druid_broker_port=8082 &"
  register: out
  args:
    executable: /bin/bash