- name: template values.yaml file
  vars:
    secor_job_list: "{{ job_names_to_deploy.split(',')|list }}"
  template:
    src: "{{ chart_path }}/values.j2"
    dest: "{{ chart_path }}/values.yaml"
    
# - name: remove the job.batch
#   shell: kubectl delete statefulsets {{ item }} -n {{ secor_namespace }}
#   with_items:
#     - "{{ job_names_to_deploy.split(',')|list }}"
#   ignore_errors: yes

- name: helm upgrade
  shell: helm --debug upgrade --install {{ item }} {{ chart_path }} -n {{ secor_namespace }}
  with_items:
    - "{{ job_names_to_deploy.split(',')|list }}"