---
- name: Copy api conf
  template: src=kibana-nginx.conf dest=/etc/nginx/sites-available/kibana
  sudo: yes

- name: create soft link
  file: path=/etc/nginx/sites-enabled/kibana src=/etc/nginx/sites-available/kibana state=link
  sudo: yes

- name: Restart nginx
  service: name=nginx state=restarted
  sudo: yes
