version: 2.1
jobs:
  ep-build:
    working_directory: ~/dp/data-pipeline-flink
    machine: true
    steps:
      - checkout:
          path: ~/dp
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
        name: data-pipeline-flink-build
        command: mvn scoverage:report
      - run:
          name: sonar
          command: |
                 mvn -X sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-data-pipeline -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.scala.coverage.reportPaths=/home/circleci/project/telemetry-extractor/target/scoverage.xml,/home/circleci/project/pipeline-preprocessor/target/scoverage.xml,/home/circleci/project/dp-core/target/scoverage.xml,/home/circleci/project/de-duplication/target/scoverage.xml

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - ep-build
#testing quality gate