version: 2.1
jobs:
  ep-build:
    working_directory: ~/dp/data-pipeline
    machine: true
    steps:
      - checkout:
          path: ~/dp

      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}

      - run: mvn -Dlog4j.configuration=./logs -Dcobertura.report.format=xml clean cobertura:cobertura package

      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2

      - run:
          name: sonar
          command: |
             prnumber=$(echo $CI_PULL_REQUEST | awk -F'/' '{print $NF}')
             mvn verify sonar:sonar -Dsonar.pullrequest.key=$prnumber
            
workflows:
  version: 2.1
  build_and_test:
    jobs:
      - ep-build:
            context: SonarCloud
