version: 2.1
jobs:
  ep-build:
    working_directory: ~/dp/data-pipeline-flink
    machine: true
    steps:
      - checkout:
          path: ~/dp
      - restore_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
      - save_cache:
          key: dependency-cache-{{ checksum "pom.xml" }}
          paths: ~/.m2
      - run:
          name: sonar
          command: |
                mvn scoverage:report -Dlog4j.configuration=./logs sonar:sonar -Dsonar.projectKey=project-sunbird_sunbird-data-pipeline -Dsonar.organization=project-sunbird -Dsonar.host.url=https://sonarcloud.io -Dsonar.coverage.jacoco.xmlReportPaths=/home/circleci/dp/data-pipeline-flink/telemetry-extractor/target/scoverage.xml,/home/circleci/dp/data-pipeline-flink/de-duplication/target/coverage.xml,/home/circleci/dp/data-pipeline-flink/dp-core/target/coverage.xml,/home/circleci/dp/data-pipeline-flink/dp-telemetry-reader/targe/coverage.xml

workflows:
  version: 2.1
  build_and_test:
    jobs:
      - ep-build
#testing quality gate
