---
# Druid Template variables

#Common Varibles

druid_zookeeper_host: "172.17.0.4:2181"
druid_postgres_host: "172.17.0.3"
druid_postgres_user: "druid"
#druid_postgres_pass: "secrets file"

druid_default_tmp_dir: "/var/tmp"
druid_gc_logdir: "/var/gclog"
druid_log_dir: "/var/log/druid/"

#azure config

azure_account: "sunbirddevtelemetry"
#azure_key: "secrets file"
azure_container: "test-container"

#Druid Extensions

druid_storge_type: "azure"

druid_extensions_list : '"druid-azure-extensions", "graphite-emitter", "postgresql-metadata-storage", "druid-kafka-indexing-service"'

druid_community_extensions:
  - graphite-emitter
  - druid-azure-extensions

# End of druid_extensions

druid_indexing_logs_type: file
druid_indexing_log_dir: var/druid/indexing-logs
druid_indexing_storage_type : metadata
druid_indexing_task_basedir : "{{ druid_path }}var/task"

druid_common_monitors: '"com.metamx.metrics.JvmMonitor","org.apache.druid.java.util.metrics.JvmMonitor"'
druid_common_emitters: '"graphite", "logging"'

#use 2004 if using pickle , which is default else use 2003 for plaintext refer to 'druid.emitter.graphite.protocol'
druid_graphite_host: "172.17.0.4"
druid_graphite_port : 2004
druid_grpahite_prefix: "druid.test"
druid_whitelist_filepath: "{{ druid_path }}whitelist"

#End of Common variables

#Coordinator Configurations

druid_coordinator_port: 8081
druid_coordinator_service : druid/coordinator

druid_coordinator_heap_size: 128m
druid_coordinator_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_coordinator_gc_logfile: "{{ druid_gc_logdir }}/gc.log"



#Overlord Configurations
druid_overlord_port: 8090
druid_overlord_service : druid/overlord

druid_overlord_heap_size: 256m
druid_overlord_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_overlord_gc_logfile: "{{ druid_gc_logdir }}/gc_overlord.log"



# Broker Configurations
druid_broker_port: 8082
druid_broker_service: druid/broker

druid_broker_heap_size: 128m
druid_broker_max_direct_size: 800m
druid_broker_tmp_dir: /var/tmp
druid_broker_gc_logdir: "{{ druid_gc_logdir }}/gc.log"

druid_broker_http_numConnections: 5
druid_broker_server_http_numThread: 25

druid_broker_processing_bufferBytes: 134217728
druid_broker_processing_threads: 2


# Historical Configurations

druid_historical_port: 8083
druid_historical_service: druid/historical

druid_historical_heap_size: 128m
druid_historical_max_direct_size: 800m
druid_historical_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_historical_gc_logfile: "{{ druid_gc_logdir }}/gc_historical.log"

druid_historical_http_numConnections: 5
druid_historical_server_http_numThread: 25

druid_historical_processing_bufferBytes: 134217728
druid_historical_processing_threads: 2


druid_historical_monitoring_monitors: '"org.apache.druid.server.metrics.HistoricalMetricsMonitor","com.metamx.metrics.JvmMonitor"'

druid_historical_segmentcache_path: "{{ druid_path }}var/segmentstore"
druid_historical_segmentcache_size: 10000000000

druid_historical_server_maxsize: 10000000000


#Middle Manager

druid_middlemanager_port: 8091
druid_middlemanager_service: druid/middlemanager

druid_middlemanager_heap_size: 128m
druid_middlemanager_tmp_dir: "{{ druid_default_tmp_dir }}"
druid_middlemanager_gc_logdir: "{{ druid_gc_logdir }}/gc.log"

druid_middlemanager_worker_cap: 2
druid_mm_java_opts_array: "-server -Xmx900m -XX:+UseG1GC -XX:MaxGCPauseMillis=100 -XX:+PrintGCDetails -XX:+PrintGCTimeStamps"

druid_middlemanager_peon_server_http_numThread: 25
druid_middlemanager_peon_processing_bufferBytes: 25000000
druid_middlemanager_peon_processing_threads: 2


druid_middlemanager_peon_segmentcache_path: "{{ druid_path }}var/segment_cache"
druid_middlemanager_peon_server_maxsize: 0
