remote_user: druid
broker_port: 8082
druid_home: /home/druid
desktop_pdata_id: "{{env}}.sunbird.desktop"

ingestion_spec_configs:
  raw_telemetry_events:
    minTaskMemory: 200m
    maxTaskMemory: 400m
