---
- hosts: all
  remote_user: ecosystem
  sudo: yes
  roles:
    - timezone
  tags:
    - misc

- hosts: es
  remote_user: ecosystem
  sudo: yes
  roles:
    - rvm1-ansible
  tags:
    - ruby

- hosts: es
  remote_user: ecosystem
  pre_tasks:
    name: Update
    command: bash -lc "apt-get update"
    sudo: yes
  roles:
    - elasticsearch
  tags:
    - es

- hosts: kibana
  remote_user: ecosystem
  pre_tasks:
    name: Update
    command: bash -lc "apt-get update"
    sudo: yes
  roles:
    - utils
    - kibana
    - nginx
    - kibana_nginx
    - modify_kibana
  tags:
    - kibana

- hosts: api
  remote_user: ecosystem
  pre_tasks:
    name: Update
    command: bash -lc "apt-get update"
    sudo: yes
  roles:
    - api
    - nginx
    - api_nginx
    - logstash
  vars_files:
    - 'secrets/{{env}}.yml'
  tags:
    - api
