apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.job_name }}-jobmanager
  labels:
    app: flink
    component: {{ .Values.job_name }}-jobmanager
spec:
  ports:
  - name: rpc
    port: 6123
  - name: blob
    port: 6124
  - name: query
    port: 6125
    nodePort: 30025
  - name: ui
    port: 8081
    nodePort: {{ .Values.job_nodeport }}
  type: NodePort
  selector:
    app: flink
    component: {{ .Values.job_name }}-jobmanager
