---
- name: Install nginx
  apt: name=nginx state=present
  sudo: yes

- name: Copy api conf
  template: src=kibana-nginx.conf dest=/etc/nginx/sites-available/default
  sudo: yes

- name: Restart nginx
  service: name=nginx state=restarted
  sudo: yes
