---
- name: check if kibana tar exists
  stat: path=/opt/{{ kibana_tar }}
  register: kib

- name: Get Kibana tar
  get_url: url={{ kibana_url }} dest=/opt
  sudo: yes
  when: kib.stat.exists == False

- name: untar Kibana
  unarchive: src=/opt/{{ kibana_tar }} dest=/opt copy=no
  sudo: yes

- name: change file name
  command: bash -lc "mv /opt/{{ kibana_folder }} /opt/kibana"
  sudo: yes

- name: Get kibana init script
  get_url: url={{ kibana_init }} dest=/etc/init.d mode=755
  sudo: yes

- name: add kibana
  command: bash -lc "update-rc.d kibana4 defaults 96 9"
  sudo: yes

- name: Start kibana
  service: name=kibana4 state=started
  sudo: yes