- name: Create replay-scripts folder
  become: yes
  shell: "mkdir {{ replay_script_path }}"
  tags:
    - common

- name: Copy the replay-scripts
  become: yes
  copy:
    src: "{{ artifact }}"
    dest: "{{ replay_script_path }}"
    force: yes
  tags:
    - common

- name: Unzip replay-scripts
  shell: "cd {{ replay_script_path }} && unzip {{ artifact }}"
  tags:
    - common

- name: Activate venv
  become: yes
  pip:
    name: "{{ replay_script_path }}"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "python3.6"
  tags:
    - common

- name: Install required python modules
  become: yes
  pip: 
    name: "{{ item }}"
  with_items:
    "{{ replay_script_path }}/{{ requirements_file }}"
  tags:
    - common

