- name: Create replay scripts folder
  file: path={{ replay_script_path }} state=directory owner={{ analytics_user }} group={{ analytics_group }}
  tags:
    - common

- name: Remove script directory
  become_user: "{{analytics_user}}"
  file:
    path: "{{ replay_script_path }}/replay-scripts"
    state: absent
  tags:
    - common

- name: Copy the replay scripts
  become_user: "{{analytics_user}}"
  copy:
    src: "{{ artifact }}"
    dest: "{{ replay_script_path }}"
    force: yes
  tags:
    - common

- name: Unzip replay-scripts
  become_user: "{{analytics_user}}"
  shell: "cd {{ replay_script_path }} && unzip {{ artifact }}"
  tags:
    - common

# - name: Activate venv
#   pip:
#     name: "{{ replay_script_path }}/replay_script_artifacts"
#     virtualenv: "{{ virtualenv_path }}"
#     virtualenv_python: "python3.6"
#   tags:
#     - common

- name: Install required python modules
  become_user: "{{analytics_user}}"
  pip: 
    name: "{{ item }}"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "python3.6"
    requirements: "{{ replay_script_path }}/replay-scripts/{{ requirements_file }}"
  tags:
    - common

