- name: Create replay-scripts folder
  file: path={{ replay_script_path }} state=directory owner={{ analytics_user }} group={{ analytics_group }}
  tags:
    - common

- name: Copy the replay-scripts
  copy:
    src: "{{ artifact }}"
    dest: "{{ replay_script_path }}"
    force: yes
  tags:
    - common

- name: Unzip replay-scripts
  shell: "cd {{ replay_script_path }} && unzip {{ artifact }}"
  tags:
    - common

# - name: Activate venv
#   pip:
#     name: "{{ replay_script_path }}/replay_script_artifacts"
#     virtualenv: "{{ virtualenv_path }}"
#     virtualenv_python: "python3.6"
#   tags:
#     - common

- name: Install required python modules
  pip: 
    name: "{{ item }}"
    virtualenv: "{{ virtualenv_path }}"
    virtualenv_python: "python3.6"
  with_items:
    "{{ replay_script_path }}/{{ requirements_file }}"
  tags:
    - common

