---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | sh
    creates={{ analytics_user_home }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm use --delete-prefix v10.15.3 --silent && npm config delete prefix && nvm install {{ node_version }} && nvm alias default 10.15.3"
    creates={{ analytics_user_home }}/.nvm/alias

- name: Install pm2 globally
  npm: name=pm2 state=present global=yes
  sudo: yes
  sudo_user: root