---
- name: Install nvm
  shell: >
    curl https://raw.githubusercontent.com/creationix/nvm/v{{ nvm_version }}/install.sh | sh
    creates={{ analytics_user_home }}/.nvm/nvm.sh

- name: Install node and set version
  shell: >
    /bin/bash -c "source ~/.nvm/nvm.sh && nvm install {{ node_version }} && nvm alias default 10.15.3"
    creates={{ analytics_user_home }}/.nvm/alias

- name: Install PM2
  shell: >
    curl https://getpm2.com/install.sh | sh
