---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    role: alert-rules
    app: {{ .Values.prometheus_rule_selector_app }}
    release: {{ .Values.prometheus_rule_selector_release }}
  name: {{ .Release.Name }}
  namespace: monitoring
spec:
  groups:
  - name: alertrules.secor_jobs_lag_rule
    rules:
    - alert: secor job {{ .Release.Name }} lag 
      expr: kafka_consumergroup_lag_sum{consumergroup="{{ .Values.env }}.{{ get (get $.Values.secor_jobs $.Release.Name) "consumer_group" }}", job="processing-kafka-exporter"} > {{ get (get $.Values.secor_jobs $.Release.Name) "critical_lag_threshold" }}
      for: 30m
      labels:
        severity: critical
        module: dp_lag
        alerttype: lag
      annotations:
        message: The secor job {{ .Release.Name }} lag is above threshold {{ get (get $.Values.secor_jobs $.Release.Name) "critical_lag_threshold" }}
        lag: {{`({{ humanize $value }})`}}
        job_id: {{ .Release.Name }}
        alertname: SecorJobsLag

    - alert: secor job {{ .Release.Name }} lag 
      expr: kafka_consumergroup_lag_sum{consumergroup="{{ .Values.env }}.{{ get (get $.Values.secor_jobs $.Release.Name) "consumer_group" }}", job="processing-kafka-exporter"} > {{ get (get $.Values.secor_jobs $.Release.Name) "warning_lag_threshold" }}
      for: 30m
      labels:
        severity: warning
        module: dp_lag
        alerttype: lag
      annotations:
        message: The secor job {{ .Release.Name }} lag is above threshold {{ get (get $.Values.secor_jobs $.Release.Name) "warning_lag_threshold" }}
        lag: {{`({{ humanize $value }})`}}
        job_id: {{ .Release.Name }}
        alertname: SecorJobsLag
