# Default values for k8s-prometheus-adapter..

# Url to access prometheus
prometheus:
  url: http://{{core_prom_ip.split(":")[0]}}
  port: 9090
  path: ""

rules:
  default: true
  custom: {}
  existing:
  external:
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "telemetry-extractor_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-telemetry-extractor-group",topic="{{ env_name }}.telemetry.ingest"}) by (<<.GroupBy>>)
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "ingest-router_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-ingest-router-group"}) by (consumergroup)
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "pipeline-preprocessor_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-pipeline-preprocessor-group",topic="{{ env_name }}.telemetry.raw"}) by (<<.GroupBy>>)
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "de-normalization-primary_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-de-normalization-primary-group",topic="{{ env_name }}.telemetry.unique.primary"}) by (<<.GroupBy>>)
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "de-normalization-secondary_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-de-normalization-secondary-group",topic="{{ env_name }}.telemetry.unique.secondary"}) by (<<.GroupBy>>)
  - seriesQuery: 'kafka_consumergroup_lag_sum'
    resources:
      overrides:
        namespace:
          resource: namespace
        pod:
          resource: pod
    name:
      matches: "^(.*)"
      as: "druid-validator_kafka_consumergroup_lag_sum"
    metricsQuery: sum(kafka_consumergroup_lag_sum{consumergroup="{{ env_name }}-druid-validator-group",topic="{{ env_name }}.telemetry.denorm"}) by (<<.GroupBy>>)
