- name: Copy cluster-config.json file
  template: src=cluster-config.json.j2 dest={{ analytics.home }}/cluster-config.json
  delegate_to: localhost
  tags:
    - replay-job
    - run-job
    - config-update

- name: Copy submit-script.sh file
  template: src=submit-script.j2 dest={{ analytics.home }}/submit-script.sh mode=755
  delegate_to: localhost
  tags:
    - replay-job
    - run-job
    - config-update

- name: Copy model-config.sh file
  template: src=model-config.j2 dest={{ analytics.home }}/model-config.sh
  delegate_to: localhost  
  tags:
    - replay-job
    - run-job
    - config-update

- name: Replay Job
  shell: "nohup {{ analytics.home }}/submit-script.sh --job {{ job_id }} --mode {{ mode }} --partitions {{ partitions }} --parallelisation {{ parallelisation }} --startDate {{ start_date }} --endDate {{ end_date }} --sparkMaster {{ sparkMaster }} &"
  async: "{{ (pause_min * 60) }}"
  poll: 0
  tags:
    - replay-job 

- name: Run Job
  shell: "nohup {{ analytics.home }}/submit-script.sh --job {{ job_id }} --mode {{ mode }} --partitions {{ partitions }} --parallelisation {{ parallelisation }} --sparkMaster {{ sparkMaster }} --batch_id {{ batch_id }} &"
  async: "{{ (pause_min * 60) }}"
  poll: 0
  tags:
    - run-job

- name: Submit jobs
  shell: "nohup {{ analytics.home }}/submit-script.sh --job {{ item }} --mode default --sparkMaster yarn &"
  with_items: "{{ jobs.split(',')|list }}"
  tags:
    - job-submit