---

- include: install_java.yml

- name: Add Elastic Search APT repository
  copy: src=elasticsearch.list dest=/etc/apt/sources.list.d/elasticsearch.list mode=0666
  sudo: yes

- name: Add Elastic Search repositpry key to APT
  apt_key: url=http://packages.elasticsearch.org/GPG-KEY-elasticsearch state=present
  sudo: yes

- name: Update APT cache
  apt: update_cache=yes
  sudo: yes

- name: Install Elastic Search
  apt: name=elasticsearch={{ elasticsearch_version }} state=present
  sudo: yes

- name: Creates directory
  file: path={{ elasticsearch_config }}/scripts state=directory
  sudo: yes

- name: Add convert script
  copy: src=convert_to_hours.groovy dest={{ elasticsearch_config }}/scripts/convert_to_hours.groovy mode=0666
  sudo: yes
  notify: start elasticsearch

  # Register Elasticsearch service to start on boot
- name: Ensure Elasticsearch is started on boot
  service: name=elasticsearch enabled={{ elasticsearch_service_startonboot }} state={{ elasticsearch_service_state }}
  sudo: yes
