- hosts: local
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  vars:
    ansible_connection: ssh 
    ansible_ssh_user: deployer 
    ansible_ssh_pass: "{{ azure_spark_cluster_http_password }}"
  roles:
    - azure-hdinsight-spark-cluster
  tags:
    - copy-script
    - copy-delete-script
    
- hosts: spark-hdinsight-cluster
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - provision-azure-spark-cluster
  tags:
    - spark-provision
