- hosts: local
  become: yes
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - azure-hdinsight-spark-cluster
  tags:
    - copy-script
    
- hosts: "{{groups['spark-hdinsight-cluster']}}"
  become: yes
  gather_facts: no
  vars_files:
    - "{{inventory_dir}}/secrets.yml"
  roles:
    - provision-azure-spark-cluster
  tags:
    - spark-provision
