---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Values.secor_namespace }}
  labels:
    app: secor
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  serviceName: secor
  updateStrategy:
    type: RollingUpdate
  replicas: {{ dig $.Release.Name "replicas" "" $.Values.secor_jobs }}
  selector:
    matchLabels:
      app: secor
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: secor
        release: {{ .Release.Name }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "9102"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: {{ .Release.Name }}-secor
          image: {{ .Values.image.prefix | default "" }}{{ .Values.image.repository }}:{{ .Values.image.tag }}
          # image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: "CONFIG_FILE"
              value: "{{ .Values.secor.partition.configFile }}"
            - name: "LOG4J_CONFIGURATION"
              value: "{{ .Values.secor.partition.logConfigFile }}"
            - name: "JVM_MEMORY"
              value: "{{ .Values.secor.partition.jvm.memory }}"

          volumeMounts:
           - mountPath: /opt/secor/config
             name: secor-config
           - mountPath: /opt/secor/config/logs
             name: secor-log-config
           - name: "local-var"
             mountPath: "/mnt/secor_data/message_logs/partition"
          resources:
{{ toYaml .Values.secor.partition.resources | indent 12 }}

      volumes:
       - configMap:
           name: {{ .Release.Name }}-config
         name: secor-config
       - configMap:
           name: secor-log-config
         name: secor-log-config

  volumeClaimTemplates:
    - metadata:
        name: local-var
        labels:
          app: secor
        annotations:
          volume.beta.kubernetes.io/storage-class: "{{ .Values.secor.partition.storage.class }}"
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: "{{ .Values.secor.partition.storage.size }}"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-statsd-exporter
  namespace: {{ .Values.secor_namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secor
      component: {{ .Release.Name }}-statsd-exporter
  template:
    metadata:
      labels:
        app: secor
        component: {{ .Release.Name }}-statsd-exporter
    spec:
      containers:
      - name: {{ .Release.Name }}-statsd-exporter
        image: {{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}
        imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
        ports:
        - containerPort: 9102
        - containerPort: 9125
          protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statsd-exporter-svc
  namespace: {{ .Values.secor_namespace }}
  labels:
    app: secor
    component: {{ .Release.Name }}-statsd-exporter
spec:
  ports:
  - name: udp
    port: 9125 #port to push metrics to
    protocol: UDP
    targetPort: 9125
  - name: tcp
    port: 9102 #port to fetch metrics from
    protocol: TCP
    targetPort: 9102
  selector:
    app: secor
    component: {{ .Release.Name }}-statsd-exporter
