---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-statsd-exporter
  namespace: {{ .Values.namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secor
      component: {{ .Release.Name }}-statsd-exporter
  template:
    metadata:
      labels:
        app: secor
        component: {{ .Release.Name }}-statsd-exporter
    spec:
      containers:
      - name: {{ .Release.Name }}-statsd-exporter
        image: {{ .Values.exporter.image.repository }}:{{ .Values.exporter.image.tag }}
        imagePullPolicy: {{ .Values.exporter.image.pullPolicy }}
        ports:
        - containerPort: 9102
        - containerPort: 9125
          protocol: UDP

---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-statsd-exporter-svc
  namespace: {{ .Values.secor_namespace }}
  labels:
    app: secor
    component: {{ .Release.Name }}-statsd-exporter
spec:
  ports:
  - name: udp
    port: 9125 #port to push metrics to
    protocol: UDP
    targetPort: 9125
  - name: tcp
    port: 9102 #port to fetch metrics from
    protocol: TCP
    targetPort: 9102
  selector:
    app: secor
    component: {{ .Release.Name }}-statsd-exporter
